services:
  admin-ui:
    container_name: admin-ui
    restart: always
    build:
      context: ./mangatoon-admin-ui
      dockerfile: Dockerfile
    ports:
      - "10001:3000"

  client-ui:
    container_name: client-ui
    restart: always
    build:
      context: ./mangatoon-client-ui
      dockerfile: Dockerfile
    ports:
      - "10002:3000"